export type FieldVisibilityScope = 'both' | 'web' | 'flex' | 'system';

export type AdminFieldGroupKey =
  | 'identity'
  | 'webContent'
  | 'assets'
  | 'actions'
  | 'share'
  | 'seo'
  | 'system';

export type AdminFieldKind = 'text' | 'textarea' | 'list' | 'boolean' | 'readonly';

export type AdminFieldRegistryItem = {
  key: string;
  label: string;
  group: AdminFieldGroupKey;
  visibilityScope: FieldVisibilityScope;
  helpText: string;
  isEditable: boolean;
  sortOrder: number;
  kind?: AdminFieldKind;
  placeholder?: string;
  textareaRows?: number;
  full?: boolean;
};

export type AdminFieldGroupDefinition = {
  key: AdminFieldGroupKey;
  label: string;
  description: string;
  defaultOpen?: boolean;
};

export const ADMIN_FIELD_GROUPS: AdminFieldGroupDefinition[] = [
  {
    key: 'identity',
    label: '主卡資訊',
    description: '姓名、品牌與第一眼看到的主文案，屬於最常改動的正式內容。',
    defaultOpen: true,
  },
  {
    key: 'webContent',
    label: '網頁區塊',
    description: '控制 `/card/default/` 的內容區塊、清單與顯示開關。',
    defaultOpen: true,
  },
  {
    key: 'assets',
    label: '圖片資產',
    description: '主視覺與分享圖來源，維持既有 Google Drive 上傳流程。',
    defaultOpen: true,
  },
  {
    key: 'actions',
    label: 'CTA 按鈕',
    description: '前台按鈕與 LINE Flex footer 共用的前兩顆 CTA。',
    defaultOpen: true,
  },
  {
    key: 'share',
    label: '分享 fallback',
    description: '網頁分享 fallback 與第三顆分享按鈕文案。',
    defaultOpen: true,
  },
  {
    key: 'seo',
    label: 'SEO / Metadata',
    description: '瀏覽器標題、社群預覽與非畫面直接顯示的 metadata。',
    defaultOpen: true,
  },
  {
    key: 'system',
    label: '系統欄位',
    description: '路由、版型、內部 key 與保留欄位。預設收合，避免干擾日常編輯。',
    defaultOpen: false,
  },
];

const cardRuntimeFieldRegistrySource = [
  {
    key: 'content.fullName',
    label: '姓名',
    group: 'identity',
    visibilityScope: 'both',
    helpText: '顯示在卡片主視覺、瀏覽器標題輔助文案與 LINE Flex 名稱。',
    isEditable: true,
    sortOrder: 10,
    placeholder: '例如 蘇彥宇 Sunner',
  },
  {
    key: 'content.title',
    label: '職稱',
    group: 'identity',
    visibilityScope: 'both',
    helpText: '顯示在姓名下方，也會進入 LINE Flex 內文。',
    isEditable: true,
    sortOrder: 20,
    placeholder: '例如 品牌顧問 / Creative Strategist',
  },
  {
    key: 'content.brandName',
    label: '品牌名稱',
    group: 'identity',
    visibilityScope: 'both',
    helpText: '顯示在卡片頂部與 LINE Flex 品牌列。',
    isEditable: true,
    sortOrder: 30,
    placeholder: '例如 SUNNER Studio',
  },
  {
    key: 'content.headline',
    label: '主標',
    group: 'identity',
    visibilityScope: 'web',
    helpText: '顯示在卡片主視覺文案區，也作為 Web Share fallback 文字來源之一。',
    isEditable: true,
    sortOrder: 40,
    kind: 'textarea',
    textareaRows: 2,
    full: true,
  },
  {
    key: 'content.subheadline',
    label: '副標',
    group: 'identity',
    visibilityScope: 'web',
    helpText: '只顯示在 `/card/default/` 主視覺區，Flex 不使用這個欄位。',
    isEditable: true,
    sortOrder: 50,
    kind: 'textarea',
    textareaRows: 2,
    full: true,
  },
  {
    key: 'content.intro',
    label: '介紹文字',
    group: 'identity',
    visibilityScope: 'both',
    helpText: '顯示於前台介紹區，也會進入 LINE Flex 內文摘要。',
    isEditable: true,
    sortOrder: 60,
    kind: 'textarea',
    textareaRows: 5,
    full: true,
  },
  {
    key: 'content.highlightsTitle',
    label: '重點區標題',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '顯示在前台 highlights 區塊標題，Flex 不使用。',
    isEditable: true,
    sortOrder: 110,
  },
  {
    key: 'content.highlights',
    label: '重點條列',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '前台 highlights 清單，每行一筆；Flex 不顯示這組內容。',
    isEditable: true,
    sortOrder: 120,
    kind: 'list',
    textareaRows: 5,
    full: true,
  },
  {
    key: 'content.actionsTitle',
    label: '行動區標題',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '顯示在前台按鈕區塊標題，Flex 不使用。',
    isEditable: true,
    sortOrder: 130,
  },
  {
    key: 'content.actionsDescription',
    label: '行動區說明',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '顯示在前台按鈕區塊上方說明，Flex 不使用。',
    isEditable: true,
    sortOrder: 140,
    kind: 'textarea',
    textareaRows: 3,
    full: true,
  },
  {
    key: 'content.sharePanelTitle',
    label: '分享區標題',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '顯示在前台分享面板標題，Flex 不使用。',
    isEditable: true,
    sortOrder: 150,
    placeholder: '例如 分享這張名片',
  },
  {
    key: 'modules.showHighlights',
    label: '顯示重點區',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '控制 `/card/default/` 是否顯示 highlights 區塊。',
    isEditable: true,
    sortOrder: 160,
    kind: 'boolean',
  },
  {
    key: 'modules.showSharePanel',
    label: '顯示分享面板',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '控制前台分享提示面板是否顯示，不影響實際分享功能。',
    isEditable: true,
    sortOrder: 170,
    kind: 'boolean',
  },
  {
    key: 'modules.showQrCode',
    label: '顯示 QR Code',
    group: 'webContent',
    visibilityScope: 'web',
    helpText: '控制前台 QR Code 區塊是否顯示。',
    isEditable: true,
    sortOrder: 180,
    kind: 'boolean',
  },
  {
    key: 'photo.src',
    label: '正式圖片 URL',
    group: 'assets',
    visibilityScope: 'both',
    helpText: '卡片主視覺與 LINE Flex hero image 共用這個欄位。',
    isEditable: true,
    sortOrder: 210,
    full: true,
  },
  {
    key: 'photo.alt',
    label: '照片替代文字',
    group: 'assets',
    visibilityScope: 'web',
    helpText: '供網頁圖片無障礙與管理台預覽使用，Flex 不讀這個欄位。',
    isEditable: true,
    sortOrder: 220,
  },
  {
    key: 'photo.link',
    label: '照片點擊連結',
    group: 'assets',
    visibilityScope: 'web',
    helpText: '點擊前台主視覺圖片後導向的位置，Flex 不使用。',
    isEditable: true,
    sortOrder: 230,
  },
  {
    key: 'actions.0.label',
    label: '第一按鈕文案',
    group: 'actions',
    visibilityScope: 'both',
    helpText: '顯示在前台第一顆按鈕與 LINE Flex footer 第一顆按鈕。',
    isEditable: true,
    sortOrder: 310,
  },
  {
    key: 'actions.0.url',
    label: '第一按鈕連結',
    group: 'actions',
    visibilityScope: 'both',
    helpText: '前台第一顆按鈕與 LINE Flex footer 第一顆按鈕共用連結。',
    isEditable: true,
    sortOrder: 320,
  },
  {
    key: 'actions.0.tone',
    label: '第一按鈕樣式',
    group: 'actions',
    visibilityScope: 'web',
    helpText: '只影響前台按鈕顏色；LINE Flex footer 仍使用固定 primary/secondary 樣式。',
    isEditable: true,
    sortOrder: 330,
  },
  {
    key: 'actions.0.enabled',
    label: '啟用第一按鈕',
    group: 'actions',
    visibilityScope: 'web',
    helpText: '關閉後前台不顯示第一顆按鈕；Flex 也會因文案為空而失去對應內容。',
    isEditable: true,
    sortOrder: 340,
    kind: 'boolean',
  },
  {
    key: 'actions.1.label',
    label: '第二按鈕文案',
    group: 'actions',
    visibilityScope: 'both',
    helpText: '顯示在前台第二顆按鈕與 LINE Flex footer 第二顆按鈕。',
    isEditable: true,
    sortOrder: 350,
  },
  {
    key: 'actions.1.url',
    label: '第二按鈕連結',
    group: 'actions',
    visibilityScope: 'both',
    helpText: '前台第二顆按鈕與 LINE Flex footer 第二顆按鈕共用連結。',
    isEditable: true,
    sortOrder: 360,
  },
  {
    key: 'actions.1.tone',
    label: '第二按鈕樣式',
    group: 'actions',
    visibilityScope: 'web',
    helpText: '只影響前台按鈕顏色；LINE Flex footer 仍使用固定 secondary 樣式。',
    isEditable: true,
    sortOrder: 370,
  },
  {
    key: 'actions.1.enabled',
    label: '啟用第二按鈕',
    group: 'actions',
    visibilityScope: 'web',
    helpText: '關閉後前台不顯示第二顆按鈕。',
    isEditable: true,
    sortOrder: 380,
    kind: 'boolean',
  },
  {
    key: 'share.buttonLabel',
    label: '分享按鈕文案',
    group: 'share',
    visibilityScope: 'web',
    helpText: '只影響前台第三顆分享按鈕；Flex 的轉分享按鈕文案由系統固定。',
    isEditable: true,
    sortOrder: 410,
  },
  {
    key: 'share.title',
    label: '分享標題',
    group: 'share',
    visibilityScope: 'web',
    helpText: 'Web Share fallback 會優先使用，Flex 不讀這個欄位。',
    isEditable: true,
    sortOrder: 420,
  },
  {
    key: 'share.text',
    label: '分享文字',
    group: 'share',
    visibilityScope: 'web',
    helpText: 'Web Share 與文字分享 fallback 使用的描述文字，Flex 不使用。',
    isEditable: true,
    sortOrder: 430,
    kind: 'textarea',
    textareaRows: 4,
    full: true,
  },
  {
    key: 'seo.title',
    label: 'SEO Title',
    group: 'seo',
    visibilityScope: 'system',
    helpText: '寫入瀏覽器 title 與搜尋結果標題，不進入 Flex。',
    isEditable: true,
    sortOrder: 510,
  },
  {
    key: 'seo.description',
    label: 'SEO Description',
    group: 'seo',
    visibilityScope: 'system',
    helpText: '寫入搜尋描述與 metadata，不進入 Flex。',
    isEditable: true,
    sortOrder: 520,
    kind: 'textarea',
    textareaRows: 3,
    full: true,
  },
  {
    key: 'seo.ogTitle',
    label: 'OG Title',
    group: 'seo',
    visibilityScope: 'system',
    helpText: '社群分享卡片標題，屬於 Open Graph metadata。',
    isEditable: true,
    sortOrder: 530,
  },
  {
    key: 'seo.ogDescription',
    label: 'OG Description',
    group: 'seo',
    visibilityScope: 'system',
    helpText: '社群分享卡片描述，屬於 Open Graph metadata。',
    isEditable: true,
    sortOrder: 540,
    kind: 'textarea',
    textareaRows: 3,
    full: true,
  },
  {
    key: 'seo.ogImage',
    label: 'OG Image URL',
    group: 'seo',
    visibilityScope: 'system',
    helpText: '社群預覽圖來源，不直接顯示在卡片或 Flex 畫面。',
    isEditable: true,
    sortOrder: 550,
    full: true,
  },
  {
    key: 'slug',
    label: 'Slug',
    group: 'system',
    visibilityScope: 'system',
    helpText: '正式卡片路由主鍵；前台載入、儲存與分享流程都依賴這個值。',
    isEditable: false,
    sortOrder: 610,
    kind: 'readonly',
  },
  {
    key: 'id',
    label: 'Card ID',
    group: 'system',
    visibilityScope: 'system',
    helpText: '內部卡片識別碼，目前用於 bundled config 與本地草稿 key。',
    isEditable: false,
    sortOrder: 620,
    kind: 'readonly',
  },
  {
    key: 'isPrimary',
    label: 'Primary Card',
    group: 'system',
    visibilityScope: 'system',
    helpText: '標記 bundled 預設卡片，屬於系統保留欄位。',
    isEditable: false,
    sortOrder: 630,
    kind: 'readonly',
  },
  {
    key: 'legacySlugs',
    label: 'Legacy Slugs',
    group: 'system',
    visibilityScope: 'system',
    helpText: '保留舊路由別名，供 canonical slug 對應使用；不直接顯示在卡片。',
    isEditable: false,
    sortOrder: 640,
    kind: 'readonly',
  },
  {
    key: 'appearance.theme',
    label: 'Theme',
    group: 'system',
    visibilityScope: 'web',
    helpText: '控制前台主題 preset；目前只有 bundled 既定值，管理台先只讀顯示。',
    isEditable: false,
    sortOrder: 650,
    kind: 'readonly',
  },
  {
    key: 'appearance.layout',
    label: 'Layout',
    group: 'system',
    visibilityScope: 'web',
    helpText: '控制前台版型 className；目前只有既定 layout，管理台先只讀顯示。',
    isEditable: false,
    sortOrder: 660,
    kind: 'readonly',
  },
  {
    key: 'actions.0.id',
    label: '第一按鈕 ID',
    group: 'system',
    visibilityScope: 'system',
    helpText: '按鈕內部 key，供 React key 與設定辨識使用。',
    isEditable: false,
    sortOrder: 670,
    kind: 'readonly',
  },
  {
    key: 'actions.1.id',
    label: '第二按鈕 ID',
    group: 'system',
    visibilityScope: 'system',
    helpText: '按鈕內部 key，供 React key 與設定辨識使用。',
    isEditable: false,
    sortOrder: 680,
    kind: 'readonly',
  },
] satisfies AdminFieldRegistryItem[];

export const CARD_RUNTIME_FIELD_REGISTRY: AdminFieldRegistryItem[] = [...cardRuntimeFieldRegistrySource].sort(
  (left, right) => left.sortOrder - right.sortOrder,
);

export const ADMIN_FIELD_GROUPS_BY_KEY = Object.fromEntries(
  ADMIN_FIELD_GROUPS.map((group) => [group.key, group]),
) as Record<AdminFieldGroupKey, AdminFieldGroupDefinition>;

export const CARD_RUNTIME_FIELDS_BY_GROUP = Object.fromEntries(
  ADMIN_FIELD_GROUPS.map((group) => [
    group.key,
    CARD_RUNTIME_FIELD_REGISTRY.filter((field) => field.group === group.key),
  ]),
) as Record<AdminFieldGroupKey, AdminFieldRegistryItem[]>;
